export default class AnotacaoSistemaRhEntity {
  _idAnotacao;
  _responsavel;
  _anotacao;
  _atestado;
  _ferias;
  _faltou;
  _suspensao;
  _licenca;
  _atestadohora;
  _advertenciaEscrita;
  _advertenciaVerbal;
  _horaExtra;
  _dataInicio;
  _dataFinal;
  _dataAdvEscrita;
  _bancoPositivo;
  _bancoNegativo;
  _colaborador;
  _tipo;
  _motivo;
  _atraso;
  _status;
  _atrasoInt;
}
